version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: resume
      MONGO_INITDB_ROOT_PASSWORD: resume
      MONGO_INITDB_DATABASE: resume
    networks:
      - mynet

  mongoclient:
    image: mongoclient/mongoclient:latest
    container_name: mongoclient
    hostname: mongoclient
    depends_on:
      - mongodb
    networks:
      - mynet
    ports:
      - 3300:3000

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: scoreapi
    ports:
      - "8000:8000"
    networks:
      - mynet
    

volumes:
  mongodb_data_container:

networks:
  mynet:
