version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: yourusername
      MONGO_INITDB_ROOT_PASSWORD: yourpassword
    networks:
      - mynet

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yourusername
      ME_CONFIG_MONGODB_ADMINPASSWORD: yourpassword
    networks:
      - mynet


  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: scoreapi
    ports:
      - "8000:8000"
    networks:
      - mynet
    

volumes:
  mongodb_data_container:

networks:
  mynet:
